import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { isToday, startOfWeek, endOfWeek, parseISO, startOfMonth, endOfMonth, eachDayOfInterval, isSameDay, isSameMonth, format } from 'date-fns';
import { es } from 'date-fns/locale';
import {
    CalendarDays,
    UserPlus,
    Mail,
    Scissors,
    Zap,
    BarChart3,
    TrendingUp,
    Users,
} from 'lucide-react';
import DashboardLayout from '@/components/common/DashboardLayout';
import { ConfirmDialog } from '@/components/common/ConfirmDialog';
import { CancelAppointmentDialog } from '@/components/appointments/CancelAppointmentDialog';
import { useAppointmentsStore } from '@/stores/appointmentsStore';
import { useBookingRequestsStore } from '@/stores/bookingRequestsStore';
import { useCustomersStore } from '@/stores/customersStore';
import { Appointment, AppointmentStatus } from '@/types/appointment.types';
import { BookingRequest } from '@/types/booking.types';
import { ServiceSummary } from '@/types/service.types';
import { statsApi } from '@/api/stats.api';
import { DashboardStats } from '@/types/stats.types';
import { useCalendarDisplayConfig } from '@/hooks/useCalendarDisplayConfig';
import { getDayDotColors } from '@/utils/calendarDisplay';
import { useToast } from '@/hooks/useToast';

// ─── helpers ────────────────────────────────────────────────────────────────

const formatCurrency = (value: number) => `$${value.toLocaleString('es-CL')}`;

function getAppointmentServices(apt: Appointment): ServiceSummary[] {
    if (apt.services && apt.services.length > 0) return apt.services;
    return apt.service ? [apt.service] : [];
}

function getAppointmentTotal(apt: Appointment): number {
    // 1. Try to extract total from notes (generated by our creation summary)
    // This takes precedence because it includes manually added extras
    if (apt.notes) {
        // Regex robusta para capturar el total ignorando puntos de miles y espacios
        const match = apt.notes.match(/Total final estimado:\s*\$?\s*([\d.]+)/i);
        if (match && match[1]) {
            const parsedTotal = parseInt(match[1].replace(/\./g, ''), 10);
            if (!isNaN(parsedTotal) && parsedTotal > 0) return parsedTotal;
        }
    }

    // 2. Fallback to API totalPrice field (manual edits saved)
    if (typeof apt.totalPrice === 'number' && apt.totalPrice > 0) return apt.totalPrice;

    // 3. Fallback to sum of services
    return getAppointmentServices(apt).reduce((sum, service) => sum + service.price, 0);
}

function statusLabel(status: AppointmentStatus): string {
    const map: Record<AppointmentStatus, string> = {
        PENDING:   'Pendiente',
        CONFIRMED: 'Confirmada',
        COMPLETED: 'Completada',
        CANCELLED: 'Cancelada',
    };
    return map[status] ?? status;
}

function statusPillStyle(status: AppointmentStatus): React.CSSProperties {
    switch (status) {
        case AppointmentStatus.PENDING:
            return { background: '#fde8cc', color: '#7c4a00' };
        case AppointmentStatus.CONFIRMED:
            return { background: '#d4edda', color: '#155724' };
        case AppointmentStatus.COMPLETED:
            return { background: '#c8e6e0', color: '#0d5c4a' };
        case AppointmentStatus.CANCELLED:
            return { background: '#fce4e4', color: '#7c1c1c' };
        default:
            return { background: '#e9ecef', color: '#495057' };
    }
}

// ─── sub-components ──────────────────────────────────────────────────────────

function SectionTitle({ children }: { children: React.ReactNode }) {
    return (
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '20px' }}>
            <span style={{ flex: 1, height: '1px', background: '#d4a89a' }} />
            <span style={{ color: '#8b6f5e', fontSize: '15px', fontWeight: 500, letterSpacing: '0.03em', whiteSpace: 'nowrap' }}>
                {children}
            </span>
            <span style={{ flex: 1, height: '1px', background: '#d4a89a' }} />
        </div>
    );
}

function DashCard({ children, style = {} }: { children: React.ReactNode; style?: React.CSSProperties }) {
    return (
        <div style={{
            background: 'rgba(255,255,255,0.88)',
            borderRadius: '20px',
            border: '1px solid rgba(240,224,216,0.7)',
            boxShadow: '0 2px 12px rgba(180,120,100,0.08)',
            overflow: 'hidden',
            ...style,
        }}>
            {children}
        </div>
    );
}

// Botón de acción — texto siempre dentro, ícono arriba en móvil si es necesario
type ActionVariant = 'rose' | 'mint' | 'beige' | 'sky';
const variantStyles: Record<ActionVariant, { bg: string; hover: string; text: string; icon: string }> = {
    rose:  { bg: '#fce8e4', hover: '#f9d5cf', text: '#7c3a2d', icon: '#c9897a' },
    mint:  { bg: '#e8f5f0', hover: '#d4ede6', text: '#2d6b55', icon: '#5a9e82' },
    beige: { bg: '#f5ede8', hover: '#eeddd6', text: '#6b4c38', icon: '#b07a5e' },
    sky:   { bg: '#e8f0f8', hover: '#d4e4f2', text: '#2d4f7c', icon: '#5a7eb0' },
};

function ActionButton({ icon, label, to, variant }: {
    icon: React.ReactNode; label: string; to: string; variant: ActionVariant;
}) {
    const s = variantStyles[variant];
    return (
        <Link to={to} style={{ display: 'block', textDecoration: 'none' }}>
            <div
                style={{
                    background: s.bg,
                    borderRadius: '12px',
                    padding: '12px 10px',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '6px',
                    cursor: 'pointer',
                    transition: 'background 0.15s',
                    minHeight: '72px',
                    textAlign: 'center',
                }}
                onMouseEnter={e => (e.currentTarget.style.background = s.hover)}
                onMouseLeave={e => (e.currentTarget.style.background = s.bg)}
            >
                <span style={{ color: s.icon, display: 'flex' }}>{icon}</span>
                <span style={{
                    color: s.text,
                    fontSize: '12px',
                    fontWeight: 600,
                    lineHeight: '1.3',
                    wordBreak: 'break-word',
                    width: '100%',
                }}>
                    {label}
                </span>
            </div>
        </Link>
    );
}

function Spinner() {
    return (
        <div style={{
            width: '28px', height: '28px', borderRadius: '50%',
            border: '3px solid #f0d0c8', borderTopColor: '#c9897a',
            animation: 'spin 0.8s linear infinite',
        }} />
    );
}

const weekDayNames = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'];

// ─── main page ───────────────────────────────────────────────────────────────

export default function DashboardPage() {
    const navigate = useNavigate();
    const toast = useToast();
    const { appointments, isLoading: appointmentsLoading, fetchAppointments, updateAppointmentStatus, updateAppointment } = useAppointmentsStore();
    const { bookingRequests, fetchBookingRequests } = useBookingRequestsStore();
    const { customers, fetchCustomers } = useCustomersStore();
    const [statsLoading, setStatsLoading] = useState(true);
    const [dashboardStats, setDashboardStats] = useState<DashboardStats | null>(null);
    const [calendarMonth] = useState(new Date());
    const calendarDisplayConfig = useCalendarDisplayConfig();
    const [completeDialog, setCompleteDialog] = useState<{ show: boolean; appointmentId: number | null }>({ show: false, appointmentId: null });
    const [showCancelModal, setShowCancelModal] = useState(false);
    const [cancelingAppointmentId, setCancelingAppointmentId] = useState<number | null>(null);
    const [isCancelLoading, setIsCancelLoading] = useState(false);

    useEffect(() => {
        const load = async () => {
            setStatsLoading(true);
            try {
                const [stats] = await Promise.all([
                    statsApi.getDashboardStats(),
                    fetchAppointments(), 
                    fetchBookingRequests(), 
                    fetchCustomers()
                ]);
                setDashboardStats(stats);
            } catch (error) {
                console.error("Error loading dashboard stats:", error);
            } finally {
                setStatsLoading(false);
            }
        };
        load();
    }, [fetchAppointments, fetchBookingRequests, fetchCustomers]);

    const handleCompleteAppointment = async () => {
        if (!completeDialog.appointmentId) return;
        
        try {
            await updateAppointmentStatus(completeDialog.appointmentId, AppointmentStatus.COMPLETED);
            toast.success('Cita marcada como completada');
            setCompleteDialog({ show: false, appointmentId: null });
        } catch (error) {
            toast.error('Error al completar cita');
        }
    };

    const handleCancelAppointment = (id: number) => {
        setCancelingAppointmentId(id);
        setShowCancelModal(true);
    };

    const handleConfirmCancelAppointment = async (reason: string) => {
        if (!cancelingAppointmentId) return;

        setIsCancelLoading(true);
        try {
            const appointment = appointments.find((apt) => apt.id === cancelingAppointmentId);
            if (!appointment) throw new Error('Cita no encontrada');

            const updatedNotes = appointment.notes
                ? `${appointment.notes}\n\n--- CANCELACIÓN ---\nMotivo: ${reason}`
                : `--- CANCELACIÓN ---\nMotivo: ${reason}`;

            await updateAppointmentStatus(cancelingAppointmentId, AppointmentStatus.CANCELLED);
            await updateAppointment(cancelingAppointmentId, { notes: updatedNotes });

            toast.success('Cita cancelada correctamente');
            setShowCancelModal(false);
            setCancelingAppointmentId(null);
            await fetchAppointments();
        } catch (err) {
            toast.error(err instanceof Error ? err.message : 'Error al cancelar la cita');
        } finally {
            setIsCancelLoading(false);
        }
    };

    const todayAppointments = appointments.filter(
        (apt: Appointment) => apt.appointmentDate && isToday(parseISO(apt.appointmentDate))
    );
    const thisWeekAppointments = appointments.filter((apt: Appointment) => {
        if (!apt.appointmentDate) return false;
        const d = parseISO(apt.appointmentDate);
        const weekStart = startOfWeek(new Date(), { locale: es });
        const weekEnd   = endOfWeek(new Date(),   { locale: es });
        return d >= weekStart && d <= weekEnd;
    });
    const pendingRequests = bookingRequests.filter((r: BookingRequest) => r.status === 'PENDING');

    const weekStats = [
        { label: 'Confirmadas', count: thisWeekAppointments.filter((a: Appointment) => a.status === AppointmentStatus.CONFIRMED).length, bg: '#d4edda', color: '#155724' },
        { label: 'Completadas', count: thisWeekAppointments.filter((a: Appointment) => a.status === AppointmentStatus.COMPLETED).length, bg: '#c8e6e0', color: '#0d5c4a' },
        { label: 'Pendientes',  count: thisWeekAppointments.filter((a: Appointment) => a.status === AppointmentStatus.PENDING).length,   bg: '#fde8cc', color: '#7c4a00' },
        { label: 'Canceladas',  count: thisWeekAppointments.filter((a: Appointment) => a.status === AppointmentStatus.CANCELLED).length,  bg: '#fce4e4', color: '#7c1c1c' },
    ];

    const monthCalendarCells = useMemo(() => {
        const monthStart = startOfMonth(calendarMonth);
        const monthEnd = endOfMonth(calendarMonth);
        const calendarStart = startOfWeek(monthStart, { weekStartsOn: 1 });
        const calendarEnd = endOfWeek(monthEnd, { weekStartsOn: 1 });
        const days = eachDayOfInterval({ start: calendarStart, end: calendarEnd });

        return days.map((day) => {
            const dayAppointments = appointments.filter((apt: Appointment) => {
                const aptDate = apt.appointmentDate.includes('T')
                    ? new Date(apt.appointmentDate)
                    : new Date(`${apt.appointmentDate}T00:00:00`);
                return isSameDay(aptDate, day);
            });

            return {
                date: day,
                isToday: isToday(day),
                isOutsideMonth: !isSameMonth(day, calendarMonth),
                appointmentCount: dayAppointments.length,
                dotColors: getDayDotColors(dayAppointments, calendarDisplayConfig),
            };
        });
    }, [appointments, calendarMonth, calendarDisplayConfig]);

    const PAGE_BG   = '#fdf0ec';
    const CARD_PAD  = '20px';
    const TEXT_DARK = '#5c3d2e';
    const TEXT_MID  = '#9e7b6e';
    const DIVIDER   = '1px solid #f0e0d8';

    return (
        <DashboardLayout>
            {/* inject keyframe for spinner */}
            <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>

            <div style={{ minHeight: '100vh', background: PAGE_BG, padding: '16px', display: 'flex', flexDirection: 'column', gap: '14px' }}>

                {/* ══ 1. Clientes Activos ══════════════════════════════════ */}
                <DashCard style={{ padding: CARD_PAD, textAlign: 'center' }}>
                    <SectionTitle>Clientes Activos</SectionTitle>
                    {statsLoading ? (
                        <div style={{ display: 'flex', justifyContent: 'center', padding: '16px' }}><Spinner /></div>
                    ) : (
                        <>
                            <div style={{ fontSize: '72px', fontWeight: 300, color: '#5a8f7b', lineHeight: 1, marginBottom: '6px' }}>
                                {customers.length}
                            </div>
                            <div style={{ fontSize: '14px', color: TEXT_MID }}>Total registrados</div>
                        </>
                    )}
                </DashCard>

                {/* ══ 2. Acciones Rápidas ══════════════════════════════════ */}
                <DashCard style={{ padding: CARD_PAD }}>
                    <SectionTitle>
                        <Zap size={14} style={{ display: 'inline', color: '#e8a838', marginRight: '6px', verticalAlign: 'middle' }} />
                        Acciones Rápidas
                    </SectionTitle>
                    {/* Grid 2×2 — ícono arriba, texto abajo para evitar desborde */}
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
                        <ActionButton icon={<CalendarDays size={22} />} label="Nueva Cita"          to="/appointments?create=1&returnTo=%2Fdashboard"    variant="rose" />
                        <ActionButton icon={<UserPlus    size={22} />} label="Nuevo Cliente"        to="/customers?create=1&returnTo=%2Fdashboard"       variant="mint" />
                        <ActionButton
                            icon={<Mail size={22} />}
                            label={`Ver Solicitudes${pendingRequests.length > 0 ? ` (${pendingRequests.length})` : ''}`}
                            to="/booking-requests"
                            variant="beige"
                        />
                        <ActionButton icon={<Scissors   size={22} />} label="Gestionar Servicios"  to="/services"        variant="sky"  />
                    </div>
                </DashCard>

                {/* ══ 3. Citas de Hoy ══════════════════════════════════════ */}
                <DashCard>
                    {/* header */}
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 20px 12px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <CalendarDays size={20} style={{ color: '#c9897a' }} />
                            <span style={{ fontWeight: 600, fontSize: '15px', color: TEXT_DARK }}>Citas de Hoy</span>
                        </div>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                            <div style={{ textAlign: 'right', display: 'flex', flexDirection: 'column' }}>
                                <span style={{ fontSize: '9px', textTransform: 'uppercase', color: TEXT_MID, fontWeight: 700, letterSpacing: '0.05em' }}>Total Hoy</span>
                                <span style={{ fontSize: '13px', fontWeight: 700, color: '#5a8f7b' }}>{formatCurrency(todayAppointments.filter(apt => apt.status !== 'CANCELLED').reduce((sum, apt) => sum + getAppointmentTotal(apt), 0))}</span>
                            </div>
                            <Link to="/appointments" style={{ fontSize: '13px', color: TEXT_MID, textDecoration: 'underline' }}>
                                Ver todas
                            </Link>
                        </div>
                    </div>

                    {appointmentsLoading ? (
                        <div style={{ display: 'flex', justifyContent: 'center', padding: '32px' }}><Spinner /></div>
                    ) : todayAppointments.length === 0 ? (
                        <p style={{ textAlign: 'center', color: '#b09080', fontSize: '14px', padding: '32px 20px' }}>
                            No hay citas programadas para hoy.
                        </p>
                    ) : (
                        <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
                            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px', minWidth: '340px' }}>
                                <thead>
                                    <tr style={{ borderTop: DIVIDER }}>
                                        {['Hora', 'Cliente', 'Servicio', 'Valor', 'Estado', 'Acciones'].map(h => (
                                            <th key={h} style={{
                                                textAlign: 'left', padding: '10px 12px',
                                                fontSize: '11px', fontWeight: 700,
                                                textTransform: 'uppercase', letterSpacing: '0.05em',
                                                color: TEXT_DARK, whiteSpace: 'nowrap',
                                            }}>{h}</th>
                                        ))}
                                    </tr>
                                </thead>
                                <tbody>
                                    {todayAppointments.slice(0, 5).map((apt: Appointment, idx: number) => (
                                        <tr
                                            key={apt.id}
                                            style={{
                                                borderTop: DIVIDER,
                                                background: idx % 2 !== 0 ? '#fdf6f3' : '#fff',
                                            }}
                                        >
                                            <td style={{ padding: '12px', color: TEXT_DARK, whiteSpace: 'nowrap', fontFamily: 'monospace', fontSize: '12px' }}>
                                                {apt.appointmentTime ? apt.appointmentTime.slice(0, 5) : '-'}
                                            </td>
                                            <td style={{ padding: '12px', color: TEXT_DARK, fontWeight: 500 }}>
                                                {apt.customer.fullName}
                                            </td>
                                            <td style={{ padding: '12px', color: '#7a5c50' }}>
                                                {getAppointmentServices(apt).map((s: ServiceSummary) => s.name).join(' + ') || '-'}
                                            </td>
                                            <td style={{ padding: '12px', color: '#5a8f7b', fontWeight: 600, whiteSpace: 'nowrap' }}>
                                                {formatCurrency(getAppointmentTotal(apt))}
                                            </td>
                                            <td style={{ padding: '12px', whiteSpace: 'nowrap' }}>
                                                <span style={{
                                                    ...statusPillStyle(apt.status),
                                                    display: 'inline-block',
                                                    borderRadius: '999px',
                                                    padding: '3px 10px',
                                                    fontSize: '11px',
                                                    fontWeight: 700,
                                                }}>
                                                    {statusLabel(apt.status)}
                                                </span>
                                            </td>
                                            <td style={{ padding: '12px', whiteSpace: 'nowrap' }}>
                                                <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                                                    <button
                                                        type="button"
                                                        onClick={() => navigate(`/appointments?edit=${apt.id}&returnTo=/dashboard`)}
                                                        style={{
                                                            border: '1px solid #d4a89a',
                                                            background: '#fff8f5',
                                                            color: '#7c3a2d',
                                                            borderRadius: '999px',
                                                            padding: '4px 10px',
                                                            fontSize: '12px',
                                                            fontWeight: 600,
                                                            cursor: 'pointer',
                                                        }}
                                                    >
                                                        Editar
                                                    </button>
                                                    <button
                                                        type="button"
                                                        onClick={() => navigate(`/appointments?reschedule=${apt.id}&returnTo=/dashboard`)}
                                                        style={{
                                                            border: '1px solid #b6d8cb',
                                                            background: '#eaf7f2',
                                                            color: '#1f6b52',
                                                            borderRadius: '999px',
                                                            padding: '4px 10px',
                                                            fontSize: '12px',
                                                            fontWeight: 600,
                                                            cursor: 'pointer',
                                                        }}
                                                    >
                                                        Reagendar
                                                    </button>
                                                    {apt.status !== AppointmentStatus.COMPLETED && (
                                                        <button
                                                            type="button"
                                                            onClick={() => setCompleteDialog({ show: true, appointmentId: apt.id })}
                                                            style={{
                                                                border: '1px solid #c8e6e0',
                                                                background: '#e0f5f0',
                                                                color: '#0d5c4a',
                                                                borderRadius: '999px',
                                                                padding: '4px 10px',
                                                                fontSize: '12px',
                                                                fontWeight: 600,
                                                                cursor: 'pointer',
                                                            }}
                                                        >
                                                            Completar
                                                        </button>
                                                    )}
                                                    {apt.status !== AppointmentStatus.CANCELLED && apt.status !== AppointmentStatus.COMPLETED && (
                                                        <button
                                                            type="button"
                                                            onClick={() => handleCancelAppointment(apt.id)}
                                                            style={{
                                                                border: '1px solid #f5bfbf',
                                                                background: '#fce4e4',
                                                                color: '#7c1c1c',
                                                                borderRadius: '999px',
                                                                padding: '4px 10px',
                                                                fontSize: '12px',
                                                                fontWeight: 600,
                                                                cursor: 'pointer',
                                                            }}
                                                        >
                                                            Cancelar
                                                        </button>
                                                    )}
                                                </div>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                            {todayAppointments.length > 5 && (
                                <div style={{ textAlign: 'center', padding: '10px', borderTop: DIVIDER }}>
                                    <Link to="/appointments" style={{ fontSize: '12px', color: TEXT_MID, textDecoration: 'underline' }}>
                                        Ver {todayAppointments.length - 5} más…
                                    </Link>
                                </div>
                            )}
                        </div>
                    )}
                </DashCard>

                {/* ══ 4. Resumen Semanal ═══════════════════════════════════ */}
                <DashCard style={{ padding: CARD_PAD }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '14px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <BarChart3 size={18} style={{ color: '#c9897a' }} />
                            <span style={{ fontWeight: 600, fontSize: '15px', color: TEXT_DARK }}>Resumen Semanal</span>
                        </div>
                        <span style={{ fontWeight: 700, fontSize: '20px', color: '#5a8f7b' }}>
                            {thisWeekAppointments.length}
                        </span>
                    </div>
                    <div>
                        {weekStats.map(({ label, count, bg, color }, i) => (
                            <div key={label} style={{
                                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                                padding: '9px 0',
                                borderBottom: i < weekStats.length - 1 ? DIVIDER : 'none',
                            }}>
                                <span style={{ fontSize: '14px', color: TEXT_MID }}>{label}</span>
                                <span style={{
                                    background: bg, color, fontSize: '12px', fontWeight: 700,
                                    borderRadius: '999px', padding: '2px 10px', minWidth: '28px', textAlign: 'center',
                                }}>{count}</span>
                            </div>
                        ))}
                    </div>
                </DashCard>

                {/* ══ 5. Insights de negocio ═══════════════════════════════ */}
                <DashCard style={{ padding: CARD_PAD }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
                        <TrendingUp size={18} style={{ color: '#c9897a' }} />
                        <span style={{ fontWeight: 600, fontSize: '15px', color: TEXT_DARK }}>Insights del Mes</span>
                    </div>

                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 0', borderBottom: DIVIDER }}>
                        <span style={{ fontSize: '14px', color: TEXT_MID }}>Ingresos Proyectados</span>
                        <span style={{ fontWeight: 700, fontSize: '16px', color: '#5a8f7b' }}>
                            {formatCurrency(dashboardStats?.totalRevenueMonth || 0)}
                        </span>
                    </div>

                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 0', borderBottom: DIVIDER, gap: '8px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexShrink: 0 }}>
                            <Users size={14} style={{ color: '#b09080' }} />
                            <span style={{ fontSize: '14px', color: TEXT_MID }}>Fidelidad</span>
                        </div>
                        <span style={{ fontWeight: 600, fontSize: '13px', color: TEXT_DARK, textAlign: 'right', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: '55%' }} title={dashboardStats?.topCustomer?.name}>
                            {dashboardStats?.topCustomer ? `${dashboardStats.topCustomer.name} (${dashboardStats.topCustomer.appointmentCount})` : 'Sin datos'}
                        </span>
                    </div>

                    <div style={{ paddingTop: '16px' }}>
                        <div style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: '#b09080', marginBottom: '12px' }}>
                            Ranking de Servicios
                        </div>
                        {!dashboardStats?.topServices || dashboardStats.topServices.length === 0 ? (
                            <p style={{ fontSize: '13px', color: '#c9a898' }}>Aún no hay datos de servicios.</p>
                        ) : (
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                                {dashboardStats.topServices.map((s) => {
                                    const maxRevenue = Math.max(...dashboardStats.topServices.map(ts => ts.revenue), 1);
                                    const percentage = (s.revenue / maxRevenue) * 100;
                                    return (
                                        <div key={s.name}>
                                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '4px' }}>
                                                <span style={{ fontSize: '13px', color: TEXT_DARK, fontWeight: 500, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                                                    {s.name}
                                                </span>
                                                <span style={{ fontSize: '12px', fontWeight: 600, color: TEXT_DARK }}>
                                                    {formatCurrency(s.revenue)}
                                                </span>
                                            </div>
                                            <div style={{ height: '6px', background: '#f3e9e2', borderRadius: '3px', overflow: 'hidden' }}>
                                                <div style={{ 
                                                    height: '100%', 
                                                    width: `${percentage}%`, 
                                                    background: 'linear-gradient(90deg, #c9897a, #e5b2a7)',
                                                    borderRadius: '3px',
                                                    transition: 'width 1s ease-in-out'
                                                }} />
                                            </div>
                                            <div style={{ fontSize: '10px', color: TEXT_MID, marginTop: '2px' }}>
                                                {s.count} servicios realizados este mes
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>
                        )}
                    </div>
                </DashCard>

                {/* ══ 6. Calendario del Mes (no interactivo) ═══════════════ */}
                <DashCard style={{ padding: CARD_PAD }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '14px', gap: '10px', flexWrap: 'wrap' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <CalendarDays size={18} style={{ color: '#c9897a' }} />
                            <span style={{ fontWeight: 600, fontSize: '15px', color: TEXT_DARK }}>
                                Calendario del Mes
                            </span>
                        </div>
                        <span style={{ fontSize: '13px', color: TEXT_MID, textTransform: 'capitalize' }}>
                            {format(calendarMonth, 'MMMM yyyy', { locale: es })}
                        </span>
                    </div>

                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '0.9rem' }}>
                        <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.3rem', fontSize: '11px', color: TEXT_MID }}>
                            <i style={{ width: '10px', height: '10px', borderRadius: '50%', background: calendarDisplayConfig.morning.color, display: 'inline-block' }} />
                            {calendarDisplayConfig.morning.start}-{calendarDisplayConfig.morning.end}
                        </span>
                        <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.3rem', fontSize: '11px', color: TEXT_MID }}>
                            <i style={{ width: '10px', height: '10px', borderRadius: '50%', background: calendarDisplayConfig.afternoon.color, display: 'inline-block' }} />
                            {calendarDisplayConfig.afternoon.start}-{calendarDisplayConfig.afternoon.end}
                        </span>
                        <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.3rem', fontSize: '11px', color: TEXT_MID }}>
                            <i style={{ width: '10px', height: '10px', borderRadius: '50%', background: calendarDisplayConfig.night.color, display: 'inline-block' }} />
                            {calendarDisplayConfig.night.start}-{calendarDisplayConfig.night.end}
                        </span>
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, minmax(0, 1fr))', gap: '0.35rem', marginBottom: '0.4rem' }}>
                        {weekDayNames.map((day) => (
                            <div key={day} style={{ textAlign: 'center', fontWeight: 600, fontSize: '12px', color: TEXT_MID }}>
                                {day}
                            </div>
                        ))}
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, minmax(0, 1fr))', gap: '0.35rem' }}>
                        {monthCalendarCells.map((cell, idx) => (
                            <div
                                key={idx}
                                style={{
                                    minHeight: '62px',
                                    border: '1px solid #f0e0d8',
                                    borderRadius: '12px',
                                    padding: '0.35rem',
                                    background: cell.isToday ? 'linear-gradient(135deg, #fdf6f3 0%, #fce8e4 100%)' : '#fffdfc',
                                    opacity: cell.isOutsideMonth ? 0.48 : 1,
                                }}
                            >
                                <div style={{ fontSize: '12px', fontWeight: 600, color: TEXT_DARK, marginBottom: '0.2rem' }}>
                                    {format(cell.date, 'd')}
                                </div>
                                {cell.appointmentCount > 0 && (
                                    <>
                                        <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '0.18rem', minHeight: '12px' }}>
                                            {cell.dotColors.map((color, dotIndex) => (
                                                <span
                                                    key={dotIndex}
                                                    style={{
                                                        width: '0.34rem',
                                                        height: '0.34rem',
                                                        borderRadius: '999px',
                                                        backgroundColor: color,
                                                        display: 'inline-block',
                                                    }}
                                                />
                                            ))}
                                        </div>
                                        <div style={{ marginTop: '0.15rem', fontSize: '9px', color: TEXT_MID, fontWeight: 600 }}>
                                            {cell.appointmentCount === 1 ? '1 cita' : `${cell.appointmentCount} citas`}
                                        </div>
                                    </>
                                )}
                            </div>
                        ))}
                    </div>
                </DashCard>

            </div>

            <ConfirmDialog
                show={completeDialog.show}
                title="Completar Cita"
                message="¿Estás seguro de que deseas marcar esta cita como completada?"
                variant="success"
                onConfirm={handleCompleteAppointment}
                onCancel={() => setCompleteDialog({ show: false, appointmentId: null })}
            />

            {cancelingAppointmentId && (
                <CancelAppointmentDialog
                    show={showCancelModal}
                    appointmentId={cancelingAppointmentId}
                    customerName={appointments.find((apt) => apt.id === cancelingAppointmentId)?.customer.fullName}
                    appointmentDate={appointments.find((apt) => apt.id === cancelingAppointmentId)?.appointmentDate}
                    appointmentTime={appointments.find((apt) => apt.id === cancelingAppointmentId)?.appointmentTime}
                    onConfirm={handleConfirmCancelAppointment}
                    onCancel={() => {
                        setShowCancelModal(false);
                        setCancelingAppointmentId(null);
                    }}
                    isLoading={isCancelLoading}
                />
            )}
        </DashboardLayout>
    );
}
